services:
  mongodb:
    image: mongo:6
    container_name: mongo-organization
    restart: always
    ports:
      - "27018:27017"

    environment:
      MONGO_INITDB_DATABASE: organization-api
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
